import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getMe } from "@/lib/api/user";
import { UserProvider } from "./context/user-context";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await cookies()
  const user = await getMe();
  return (
    <html
      lang="en"
      className={`${poppins.className} ${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider user={user} >
          {children}
        </UserProvider>
        </body>
    </html>
  );
}
